/**
 * Cached DOM element references. Populated once at startup.
 */

export const els = {
  grid: document.getElementById("grid"),
  search: document.getElementById("search"),
  category: document.getElementById("category"),
  compound: document.getElementById("compound"),
  knownFor: document.getElementById("known-for"),
  sort: document.getElementById("sort"),
  evidenceFilter: document.getElementById("evidence-filter"),
  stats: document.getElementById("stats"),
  loadError: document.getElementById("load-error"),
  disclaimer: document.getElementById("disclaimer"),
  footerMeta: document.getElementById("footer-meta"),
  dialog: document.getElementById("detail-dialog"),
  detailBody: document.getElementById("detail-body"),
  detailClose: document.getElementById("detail-close"),
  detailNav: document.getElementById("detail-nav"),
  detailPrev: document.getElementById("detail-prev"),
  detailNext: document.getElementById("detail-next"),
  detailNavPos: document.getElementById("detail-nav-pos"),
  detailBookmark: document.getElementById("detail-bookmark"),
  selectionCount: document.getElementById("selection-count"),
  selectVisible: document.getElementById("select-visible"),
  clearSelection: document.getElementById("clear-selection"),
  compareSelected: document.getElementById("compare-selected"),
  viewSelected: document.getElementById("view-selected"),
  tabBrowse: document.getElementById("tab-browse"),
  tabCompare: document.getElementById("tab-compare"),
  tabStats: document.getElementById("tab-stats"),
  panelBrowse: document.getElementById("panel-browse"),
  panelCompare: document.getElementById("panel-compare"),
  panelStats: document.getElementById("panel-stats"),
  compareTable: document.getElementById("compare-table"),
  statsDashboard: document.getElementById("stats-dashboard"),
  statCompounds: document.getElementById("stat-compounds"),
  statCategories: document.getElementById("stat-categories"),
  statEvidence: document.getElementById("stat-evidence"),
  statThemes: document.getElementById("stat-themes"),
  themeToggle: document.getElementById("theme-toggle"),
  backToTop: document.getElementById("back-to-top"),
  bookmarksBar: document.getElementById("bookmarks-bar"),
  shortcutsDialog: document.getElementById("shortcuts-dialog"),
};
